# Generated by Django 4.1.7 on 2023-03-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('development_tool', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.CharField(max_length=100)),
                ('simple', models.BooleanField(default=False)),
                ('feature', models.ManyToManyField(to='plans.planfeature')),
            ],
        ),
    ]
